category: "reverse"
name:     "Экзамен по истории"
points:   100
author:   kalan
description: |
    <p>На дистанционном обучении вам необходимо сдать экзамен по истории.
    <p>Ваш преподаватель создал для этого специальное программное средство.
    <p>Вы знаете, что Вениамин Витальевич очень требователен, и никаких ошибок допускать нельзя!
generator: generate.py
