category: "web"
name:     "Домашняя страница"
points:   50
author:   nsychev
description: |
    <p>Оказалось, что ещё в прошлом веке один известный
    человек создал свою домашнюю страничку. Она доступна
    сразу на нескольких языках мира.</p>
    <p>Говорят, что в одной из версий что-то спрятано.
    Сможете найти?</p>
generator: generate.py
daemon:    app/server.py
