category: "pwn"
name:     "Melodrama I"
points:   150
author:   nsychev
description: |
    <p>Твиттер-газета <em>Melodrama</em> выходит в 
    свет с 1997 года. Огромную популярность издание
    завоевало благодаря фирменным коротким заметкам — 
    их длина ограничена 140 символами. Все статьи
    перед публикацией проходят жёсткий контроль
    с помощью специального приложения, исходный код
    которого нам удалось достать.</p>
    <p>Недавно стало известно, что сотрудники
    топ-менеджмента Мелодрамы тайно писали заметки
    для другого СМИ. Сможете выяснить, что там было?</p>
generator: generate.py
multi_generator: true
daemon: app/start_server.sh
daemon_socket: melodrama1.sock
daemon_socket_type: tcp
daemon_socket_out_port: 17493
attachments_path: public/
