category: "reverse"
name:     "Расширение сознания"
points:   350
author:   vanya
description: |
    <p>Научная лаборатория по решению NP-неполных задач
    очень нервничает в связи с последними событиями.</p>
    <p>Настолько нервничает, что её сотрудники взяли — и написали...
    психотерапевта. Если вы ещё не нервничаете, поговорите с ним.</p>
generator: generate.py
attachments_path: public/
hints:
    - name: emacs
      points: 0
      text: |
        Добавлен <a href="/files/shrink/hint.jpg">скриншот</a>, иллюстрирующий процесс работы утилиты.
