category: "crypto"
name:     "IBM Selectric"
points:   200
author:   kalan
description: |
    <p>Электрическая печатная машинка IBM Selectric была большим прорывом для своего времени — россыпь вечно заедающих молоточков с буквами заменил небольшой шарик. Его легко можно было заменить, что позволяло печатать на печатной машинке различными шрифтами и на различных языках — достаточно было найти и установить подходящий шарик.</p>
    <p>Нам попался вот такой замечательный экземпляр. Какой-то он подозрительный, вам не кажется?</p>
generator: generate.py
submit_not_after: "2020-05-24T17:00:00Z"
